FROM ubuntu

ENV PORT 8080
ENV WORKDIR /tmp/web
EXPOSE ${PORT}

RUN mkdir ${WORKDIR}
COPY index.html $WORKDIR
RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN python3 -m pip install simple_http_server

CMD cd ${WORKDIR} && python3 -m simple_http_server ${PORT}
